var dir_31f826c2d976b6ddc9fb43296ba3b8ca =
[
    [ "add_signedness.h", "duplex__integer_2add__signedness_8h_source.html", null ],
    [ "comparison.h", "comparison_8h_source.html", null ],
    [ "ctors.h", "duplex__integer_2ctors_8h_source.html", null ],
    [ "digits.h", "duplex__integer_2digits_8h_source.html", null ],
    [ "divide.h", "divide_8h_source.html", null ],
    [ "forward_declaration.h", "forward__declaration_8h_source.html", null ],
    [ "from_value.h", "duplex__integer_2from__value_8h_source.html", null ],
    [ "instantiate_duplex_integer.h", "instantiate__duplex__integer_8h_source.html", null ],
    [ "is_duplex_integer.h", "is__duplex__integer_8h_source.html", null ],
    [ "is_signed.h", "duplex__integer_2is__signed_8h_source.html", null ],
    [ "modulo.h", "modulo_8h_source.html", null ],
    [ "multiply.h", "multiply_8h_source.html", null ],
    [ "numeric_limits.h", "duplex__integer_2numeric__limits_8h_source.html", null ],
    [ "operators.h", "duplex__integer_2operators_8h_source.html", null ],
    [ "remove_signedness.h", "duplex__integer_2remove__signedness_8h_source.html", null ],
    [ "rep.h", "duplex__integer_2rep_8h_source.html", null ],
    [ "rounding.h", "__impl_2duplex__integer_2rounding_8h_source.html", null ],
    [ "scale.h", "duplex__integer_2scale_8h_source.html", null ],
    [ "set_digits.h", "duplex__integer_2set__digits_8h_source.html", null ],
    [ "set_width.h", "duplex__integer_2set__width_8h_source.html", null ],
    [ "shift.h", "shift_8h_source.html", null ],
    [ "to_chars.h", "duplex__integer_2to__chars_8h_source.html", null ],
    [ "to_rep.h", "duplex__integer_2to__rep_8h_source.html", null ],
    [ "type.h", "duplex__integer_2type_8h_source.html", null ],
    [ "wants_generic_ops.h", "wants__generic__ops_8h_source.html", null ]
];